name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and audit server
        working-directory: server
        run: |
          npm ci
          npm audit --audit-level=high || true

      - name: Install and audit client
        working-directory: client
        run: |
          npm ci
          npm audit --audit-level=high || true
